# all experiments should modify these settings only as needed
default_config = dict(
    env_name='cheetah-dir',
    n_train_tasks=2,
    n_eval_tasks=2,
    latent_size=5, # dimension of the latent context vector
    net_size=256, # number of units per FC layer in each network
    path_to_weights=None, # path to pre-trained weights to load into networks
    seed_list=[0], # list of random seeds
    env_params=dict(
        n_tasks=2, # number of distinct tasks in this domain, should equal sum of train and eval tasks
        randomize_tasks=True, # shuffle the tasks after creating them
        max_episode_steps=200, # built-in max episode length for this environment
    ),
    algo_params=dict(
        meta_batch=10, # number of tasks to average the gradient across
        batch_size=512, # number of transitions in the RL batch
        num_iterations=500, # number of data sampling / training iterates
        num_initial_steps=2000, # number of transitions collected per task before training
        num_tasks_sample=5, # number of randomly sampled tasks to collect data for each iteration
        num_steps_prior=400, # number of transitions to collect per task with z ~ prior
        num_steps_posterior=0, # number of transitions to collect per task with z ~ posterior
        num_extra_rl_steps_posterior=400, # number of additional transitions to collect per task with z ~ posterior that are only used to train the policy and NOT the encoder
        num_train_steps_per_itr=2000, # number of meta-gradient steps taken per iteration
        num_evals=1, # number of independent evals
        num_steps_per_eval=600,  # number of transitions to eval on        
        embedding_batch_size=64, # number of transitions in the context batch
        embedding_mini_batch_size=64, # number of context transitions to backprop through (should equal the arg above except in the recurrent encoder case)
        max_path_length=200, # max path length for this environment
        discount=0.99, # RL discount factor
        soft_target_tau=0.005, # for SAC target network update
        policy_lr=3e-4, # learning rate for policy
        qf_lr=3e-4, # learning rate for q network
        context_lr=3e-4, # learning rate for context encoder
        replay_buffer_size=1000000,
        save_replay_buffer=False,
        save_algorithm=False,
        save_environment=False,
        reward_scale=5., # scale rewards before constructing Bellman update, effectively controls weight on the entropy of the policy
        sparse_rewards=False, # whether to sparsify rewards as determined in env
        use_information_bottleneck=False, # False makes latent context deterministic
        update_post_train=1, # how often to resample the context when collecting data during training (in trajectories)
        num_exp_traj_eval=1, # how many exploration trajs to collect before beginning posterior sampling at test time
        dump_eval_paths=False, # whether to save evaluation trajectories
        sample=1, # whether to train with stochastic (noise-sampled) trajectories 
        train_epoch=6e5, # corresponding epoch of the model used to generate meta-training trajectories
        eval_epoch=6e5, # corresponding epoch of the model used to generate meta-testing trajectories
        use_next_obs_in_context=False, # include next obs in context, decoder targets, and task dynamics targets
        allow_eval=True, # if it is True, enable evaluation
        load_eval_buffer=True,
        policy_noise=0.2,
        noise_clip=0.5,
        policy_freq=2,
        bc_weight=2.5,
        online_sample_num=200,
        ensemble_size=7,
        relabel_buffer_size=50000,
        recon_loss_weight=10,
        relabel_data_ratio=0.95,
        num_aug_neg_tasks=3,
        n_vt=0, # default cheetah-dir has two discrete tasks; continuous-task JSON profiles enable 4
        virtual_task_generation_mode='semantic', # decoder-based paths; local/global/gaussian remain available for ablations
        virtual_semantic_neighbors=2, # maximum nearby candidate task edges per anchor
        virtual_semantic_probe_batch_size=64, # per-task fit probes; another batch is held out for path validation
        virtual_semantic_refresh_interval=100, # refresh task prototypes, support probes and paths every N gradient steps
        virtual_semantic_support_radius=1.0, # nearest-neighbor RMS radius in standardized state/action coordinates
        virtual_semantic_min_shared_probes=8, # skip edges without this many mutually supported probes
        virtual_semantic_max_latent_distance_ratio=2.0, # reject edges much longer than nearby task spacing
        virtual_semantic_max_reconstruction_error=1.0, # maximum normalized endpoint reconstruction error
        virtual_semantic_reward_weight=1.0, # reward contribution to normalized decoder behavior distance
        virtual_semantic_dynamics_weight=0.0, # reward-only default; dynamics-task JSON profiles set 1
        virtual_semantic_path_nodes=7, # includes two fixed endpoints
        virtual_semantic_path_steps=8, # optimizer steps per cached path
        virtual_semantic_path_lr=0.02,
        virtual_semantic_trust_radius=0.1, # maximum path displacement relative to endpoint distance
        virtual_semantic_latent_weight=0.05, # latent-distance regularizer against decoder-insensitive shortcuts
        virtual_semantic_validation_ratio=1.25, # permitted held-out energy relative to the straight path
        virtual_semantic_alpha_min=0.1, # accepted path sampling interval
        virtual_semantic_alpha_max=0.9,
        M=1, # local: nearest-neighbor candidates; global: number of tasks mixed by Dirichlet weights
        beta=1.0, # global Dirichlet-mixing scale; unused by local interpolation
        virtual_interpolation_lambda_max=0.2, # max interpolation ratio from anchor task toward a nearby task
        virtual_interpolation_max_distance=None, # optional nearest-real-z distance filter for virtual embeddings
        virtual_gaussian_noise_std=0.05, # gaussian mode: std of isotropic noise added to real task embeddings
        consistency_loss_weight=0.5,
        consistency_use_policy_relabel_data=True, # True: relabel virtual data; False: sampled real context data
        virtual_transition_buffer_size=50000, # replay buffer size for decoder-generated virtual transitions
        virtual_transition_batch_size=256, # TD3+BC batch size sampled from the virtual transition buffer
        virtual_transition_loss_weight=0.0, # discrete cheetah-dir default; continuous-task JSON profiles enable virtual data
        virtual_transition_weight_schedule='constant', # 'constant' or 'linear_decay' by outer training iteration
        virtual_transition_weight_decay_start_itr=100, # linear_decay: keep initial weight until this iteration
        virtual_transition_weight_decay_end_itr=300, # linear_decay: reach final weight at this iteration
        virtual_transition_final_loss_weight=0.0, # linear_decay: final virtual transition sample weight
        virtual_transition_use_policy_actions=False, # False keeps real offline actions for more stable next_obs consistency
        virtual_transition_train_policy_q=True, # True: virtual transitions also train actor with -Q
        virtual_transition_train_policy_bc=False, # False avoids BC on mismatched virtual actions
        virtual_transition_use_cycle_weight=False, # True: down-weight virtual transitions with high encoder-decoder cycle error
        virtual_transition_cycle_weight_temperature=1.0, # soft weight exp(-cycle_error / temperature)
        virtual_transition_log_nearest_distance=False, # log nearest real-z distance for virtual embeddings
        virtual_transition_use_recon_weight=False, # True: adapt virtual transition weight by decoder reconstruction reliability
        virtual_transition_recon_weight_threshold=1.0, # reconstruction EMA below this threshold keeps high virtual weight
        virtual_transition_recon_weight_temperature=1.0, # softness for recon-based down-weighting
        virtual_transition_recon_weight_ema_alpha=0.05, # EMA update rate for reconstruction loss
        virtual_transition_recon_weight_min=0.0, # lower bound for recon confidence weight
        virtual_transition_recon_weight_mode='hinge_exp', # 'hinge_exp' or 'sigmoid'
    ),
    util_params=dict(
        base_log_dir='./logs',
        use_gpu=True,
        gpu_id=0,
        debug=False, # debugging triggers printing and writes logs to debug directory
        docker=False, # TODO docker is not yet supported
        #machine='non_mujoco' #non_mujoco or mujoco, when non_mujoco is chosen, can train offline in non-mujoco environments
    ),
    algo_type='gentle'
)



